# Generated by Django 4.2.23 on 2025-06-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pud_date',
            field=models.DateTimeField(verbose_name='Дата и время публикации'),
        ),
    ]
